services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile.fastapi
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app/src

  # streamlit:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.streamlit
  #   ports:
  #     - "8501:8501"
  #   volumes:
  #     - ./:/app
  #   depends_on:
  #     - fastapi
  #   environment:
  #     - BACKEND_URL=http://fastapi:8000/api
