FROM python:3.10

WORKDIR /app

RUN pip install --no-cache-dir streamlit requests

COPY ./src ./src

EXPOSE 8501

CMD ["streamlit", "run", "src/app.py", "--server.port", "8501", "--server.address", "0.0.0.0"]
